// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRx4-SOSArix2e3t7kp9fslxbvBYWoq4k',
    appId: '1:944402918219:android:a3da5f35d40c2e4d3216ce',
    messagingSenderId: '944402918219',
    projectId: 'nautilink-ba5b4',
    storageBucket: 'nautilink-ba5b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBJ_kGrCirR7Or8ax8XNIbm-qFIqghdA',
    appId: '1:944402918219:ios:25f5a5f4fc79446f3216ce',
    messagingSenderId: '944402918219',
    projectId: 'nautilink-ba5b4',
    storageBucket: 'nautilink-ba5b4.firebasestorage.app',
    iosBundleId: 'com.nautilink.nautilink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBJ_kGrCirR7Or8ax8XNIbm-qFIqghdA',
    appId: '1:944402918219:macos:25f5a5f4fc79446f3216ce',
    messagingSenderId: '944402918219',
    projectId: 'nautilink-ba5b4',
    storageBucket: 'nautilink-ba5b4.firebasestorage.app',
    iosBundleId: 'com.nautilink.nautilink',
  );

}